name: "Portfolio Workflow"

name: Code Reviewer CI CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build And Deploy
    steps:
      - name: Deploy to production